using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("com.unity.ide.vscode.tests")]
[assembly: InternalsVisibleTo("com.unity.ide.vscode.integrationtests")]

// Expose internals to the assembly (generated by Castle's DynamicProxy)
// containing Moq's generated proxy types.
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
